#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.9.6 on Thu Oct 29 22:41:10 2020
#

import numpy, matplotlib
if matplotlib.__version__ < '2.2':
    raise ValueError("Minimum Matplotlib version required: 2.2")
#
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas

import wx
import os
#from shutil import make_archive

# read from glade
import gui
# read from main solver
import rigidWink

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class MyFrame(gui.MyFrame):


    def OnChooseTargetFile(self, event):  # wxGlade: MyFrame.<event_handler>
        pathname = self.showFileDialog()
        self.text_ctrl_1.SetValue(pathname)

    def OnChooseOutputFile(self, event):  # wxGlade: MyFrame.<event_handler>
        pathname = self.showFileDialog()
        self.text_ctrl_2.SetValue(pathname)

    def showFileDialog(self):
        with wx.FileDialog(self, 'Pls, select File',
                          style=wx.DD_DEFAULT_STYLE
                                | wx.DD_DIR_MUST_EXIST
                                | wx.DD_CHANGE_DIR
                          ) as dialog:
            if dialog.ShowModal() == wx.ID_CANCEL:
                return
            return dialog.GetPath()

    def OnCancel(self, event):  # wxGlade: MyFrame.<event_handler>
        self.Destroy()

    def OnExec(self, event):  # wxGlade: MyFrame.<event_handler>

        """
        # test
        label1 = wx.StaticText(self.panel_result, wx.ID_ANY, 'hello')
        label2 = wx.StaticText(self.panel_result, wx.ID_ANY, 'Analysis Result')
        label3 = wx.StaticText(self.panel_result, wx.ID_ANY, 'Why?')

        layout = wx.BoxSizer(wx.VERTICAL)

        #cases.SetLabel('Permanent')
        layout.Add(label1, proportion=0)
        self.panel_result.SetSizer(layout)
        #layout.Add(label2, proportion=0)
        #layout.Add(cases)

        #layout.Layout()
        """

        obj = rigidWink.Winkler()

        # Force
        nn  = 1400000.0 # Axial Force, kN
        mmx = 0 # Over Turning Moment, kN.m
#        mmx = 15000000.0 # Over Turning Moment, kN.m
        mmy = 15000000.0 # Over Turning Moment, kN.m
        #mmy = 8000000.0 # Over Turning Moment, kN.m

        xx1 = []
        xx2 = []
        yy1 = []
        yy2 = []
        ndimx = []
        ndimy = []
        kb = []

        xx1.append(0.0)
        xx2.append(100.0)
        yy1.append(0.0)
        yy2.append(30.0)
        ndimx.append(100)
        ndimy.append(30)
        kb.append(50000.0)


        xx1.append(0.0)
        xx2.append(50.0)
        yy1.append(30.0)
        yy2.append(60.0)
        ndimx.append(50)
        ndimy.append(30)
        kb.append(50000.0)


        print("------------------------------")

        if obj.getModel(xx1,xx2,yy1,yy2,ndimx,ndimy,kb):
            obj.getG(xx1,xx2,yy1,yy2)
            obj.viewModel()
            print("Complete Model Making")
        else:
            del obj
            obj = rigidWink.Winkler()
            print("Fail Model Making")


        obj.solve(nn,mmx,mmy)
        print("------------------------------")
        print("Complete")

        #print(obj.x,obj.y)
        self.matplotlib_axes.scatter(obj.x,obj.y,s=1,color="black")
        self.matplotlib_axes.spines['right'].set_visible(False)
        self.matplotlib_axes.spines['top'].set_visible(False)
        #test
        self.matplotlib_axes.set_aspect('equal')
        self.matplotlib_canvas.draw()
        event.Skip()

        # 画像をパネルに表示
        # Model
        """
        image = wx.Image('db/model.png')
        image = image.Scale(680,480,wx.IMAGE_QUALITY_HIGH)
        bitmap = image.ConvertToBitmap()
        wx.StaticBitmap(self.panel_disp, -1, bitmap, pos=(0,0) )
        """
        # Stress
        image = wx.Image('db/result.png')
        image = image.Scale(680,480,wx.IMAGE_QUALITY_HIGH)
        bitmap = image.ConvertToBitmap()
        wx.StaticBitmap(self.panel_stress, -1, bitmap, pos=(0,0) )
        # Uplift
        image = wx.Image('db/uplift.png')
        image = image.Scale(680,480,wx.IMAGE_QUALITY_HIGH)
        bitmap = image.ConvertToBitmap()
        wx.StaticBitmap(self.panel_uplift, -1, bitmap, pos=(0,0) )

        # Summary テキストデータを表示
        f = open("./db/result.txt",'r')
        line = f.read()
        f.close()
        #self.text_ctrl_result.AppendText(line)
        self.text_ctrl_result.ChangeValue(line)

        # Detail テキストデータを表示
        f = open("./db/detail.txt",'r')
        line = f.read()
        f.close()
        self.text_ctrl_detail.ChangeValue(line)


        """
        obj = stiff2D.Stiff2D()
        # read data
        if obj.read_data_xlsx(target_file):
            # exe. calculation
            if obj.calc_main():
                # write result
                if obj.write_result_xlsx(output_file):
                    print('Complete')
                    dlg = wx.MessageDialog(self, 'Cal End',
                                           'Complete',
                                           wx.OK | wx.ICON_INFORMATION
                                           )
                    dlg.ShowModal()
                    dlg.Destroy()
                else:
                    print("出力ファイルの書き込みエラー")
                    dlg = wx.MessageDialog(self, 'Erro output',
                                           'Error output',
                                           wx.OK | wx.ICON_ERROR
                                           )
                    dlg.ShowModal()
                    dlg.Destroy()

            else:
                print('実行時エラー : ' + obj.error)

                dlg = wx.MessageDialog(self, 'Erro' + obj.error,
                                       'Error Execution',
                                       wx.OK | wx.ICON_ERROR
                                       )
                dlg.ShowModal()
                dlg.Destroy()

        else:
            print("入力ファイルの読み込みエラー")
            dlg = wx.MessageDialog(self, 'Error read input',
                                   'Read Error',
                                   wx.OK | wx.ICON_ERROR
                                   )
            dlg.ShowModal()
            dlg.Destroy()

        """
    def OnPlot(self, event):  # wxGlade: MyFrame.<event_handler>
        # Make Model
        obj = rigidWink.Winkler()
        if obj.getModel(xx1,xx2,yy1,yy2,ndimx,ndimy,kb):
            obj.getG(xx1,xx2,yy1,yy2)
            obj.viewModel()
            print("Complete Model Making")
        else:
            del obj
            obj = rigidWink.Winkler()
            print("Fail Model Making")

        #target_file = self.text_ctrl_1.GetValue()
        #obj.read_data_xlsx(target_file)
        #obj.write_model()

        #print(obj.xp,obj.yp)
        #for i in range(len(obj.memb)):
            #print(obj.xp[i+1],obj.yp[i+1])
            #self.matplotlib_axes.plot(obj.xp[i+1],obj.yp[i+1],color="black")

        print(obj.x,obj.y)
        #self.matplotlib_axes.plot(obj.x,obj.y,s=1,color="black")
        #self.matplotlib_canvas.draw()
        #event.Skip()
        """
        matplotlib_axes.pyplot.gca().spines['right'].set_visible(False)
        matplotlib_axes.pyplot.gca().spines['top'].set_visible(False)
        matplotlib_axes.pyplot.gca().yaxis.set_ticks_position('left')
        matplotlib_axes.pyplot.gca().xaxis.set_ticks_position('bottom')
        """



        """
        xmin = xmax = step = None
        try:
            #xmin = float( self.text_xmin.GetValue() )
            xmin = float(0)
            #self.text_xmin.SetBackgroundColour(wx.WHITE)
        except:
            #self.text_xmin.SetBackgroundColour(wx.RED)
            print('okay')
        try:
            #xmax = float( self.text_max.GetValue() )
            xmax = float(10)
            #self.text_max.SetBackgroundColour(wx.WHITE)
        except:
            #self.text_max.SetBackgroundColour(wx.RED)
            print('okay')
        try:
            #step = float( self.text_xstep.GetValue() )
            step = float(0.1)
            #self.text_xstep.SetBackgroundColour(wx.WHITE)
        except:
            #self.text_xstep.SetBackgroundColour(wx.RED)
            print('okay')

        x = numpy.arange(xmin, xmax, step)
        # build globals with some functions
        g = {}
        for name in ["sin","cos","tan","ufunc","square"]:
            g[name] = getattr(numpy, name)
            #y = eval(self.text_function.GetValue(), g, {"numpy":numpy, "x":x})
            y = eval('sin(x)', g, {"numpy":numpy, "x":x})
            self.matplotlib_axes.plot(x,y)
            self.matplotlib_canvas.draw()
            event.Skip()
        """

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
